<#
.SYNOPSIS
    iteration-workflow Project Init Wizard - Stateful Checklist Engine

.DESCRIPTION
    Reads setup-checklist.yaml, executes steps incrementally.
    State persisted to .setup-state.yaml. Supports resume and -DryRun.

.PARAMETER DryRun
    Preview all steps without execution.

.EXAMPLE
    .\init-checklist.ps1
    .\init-checklist.ps1 -DryRun

.NOTES
    Version: v1.0.1 (039 iteration, BUG-039-01 fix: temp-file JSON passing)
    Requires: Python 3.x + pyyaml for YAML parsing
#>

param(
    [switch]$DryRun = $false
)

$ErrorActionPreference = "Continue"
$ScriptDir = Split-Path $MyInvocation.MyCommand.Path -Parent
$EngineDir = (Get-Item (Split-Path $ScriptDir -Parent)).FullName
$ProjectDir = Get-Location
$ChecklistFile = Join-Path $EngineDir "project\setup-checklist.yaml"
$StateFile = Join-Path $ProjectDir ".codebuddy\skills\iteration-workflow\runtime\.setup-state.yaml"

# === Utility Functions ===

function Parse-Yaml {
    param([string]$FilePath)
    if (-not (Test-Path $FilePath)) {
        Write-Host "ERROR: Checklist file not found: $FilePath" -ForegroundColor Red
        exit 2
    }
    $pyScript = @"
import yaml, json, sys
with open(r'$FilePath', 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f)
print(json.dumps(data, ensure_ascii=False))
"@
    $json = & python -c $pyScript 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Failed to parse YAML: $json" -ForegroundColor Red
        exit 2
    }
    return $json | ConvertFrom-Json
}

function Load-State {
    param([string]$FilePath)
    if (Test-Path $FilePath) {
        try {
            $pyScript = @"
import yaml, json
with open(r'$FilePath', 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f) or {}
print(json.dumps(data, ensure_ascii=False))
"@
            $json = & python -c $pyScript 2>&1
            if ($LASTEXITCODE -eq 0) {
                $state = $json | ConvertFrom-Json
                $result = @{}
                $state.PSObject.Properties | ForEach-Object { $result[$_.Name] = $_.Value }
                return $result
            }
        } catch { }
    }
    return @{}
}

function Save-State {
    param([string]$FilePath, [hashtable]$State)
    $dir = Split-Path $FilePath -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    # BUG-039-01: Use temp file instead of embedding JSON in Python string literal.
    # PowerShell -c argument passing mangles JSON with special chars, causing
    # json.loads to receive empty/corrupted string.
    $tempJson = [System.IO.Path]::GetTempFileName()
    try {
        $stateJson = $State | ConvertTo-Json -Compress -Depth 4
        [System.IO.File]::WriteAllText($tempJson, $stateJson, [System.Text.Encoding]::UTF8)
        $pyScript = @"
import yaml, json
with open(r'$tempJson', 'r', encoding='utf-8-sig') as f:
    data = json.load(f)
with open(r'$FilePath', 'w', encoding='utf-8') as f:
    f.write('# .setup-state.yaml -- auto-generated by init-checklist.ps1\n')
    yaml.dump(data, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
print('OK')
"@
        $result = & python -c $pyScript 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host "WARNING: Failed to save state: $result" -ForegroundColor Yellow
        }
    } finally {
        Remove-Item $tempJson -ErrorAction SilentlyContinue
    }
}

function Test-YamlFields {
    param([string]$FilePath, [string[]]$Fields)
    if (-not (Test-Path $FilePath)) { return $false }
    try {
        # Same fix as BUG-039-01: use temp file for JSON to avoid
        # PowerShell -c argument mangle
        $tempJson = [System.IO.Path]::GetTempFileName()
        $fieldsJson = $Fields | ConvertTo-Json -Compress
        [System.IO.File]::WriteAllText($tempJson, $fieldsJson, [System.Text.Encoding]::UTF8)
        $pyScript = @"
import yaml, json, sys
with open(r'$FilePath', 'r', encoding='utf-8') as f:
    data = yaml.safe_load(f) or {}
with open(r'$tempJson', 'r', encoding='utf-8-sig') as f:
    fields = json.load(f)
missing = [f for f in fields if not data.get(f)]
if missing:
    print('MISSING:' + ','.join(missing))
    sys.exit(1)
print('OK')
"@
        $result = & python -c $pyScript 2>&1
        Remove-Item $tempJson -ErrorAction SilentlyContinue
        return ($LASTEXITCODE -eq 0)
    } catch {
        return $false
    }
}

function Test-NoPlaceholder {
    param([string]$FilePath, [string[]]$Placeholders)
    if (-not (Test-Path $FilePath)) { return $false }
    try {
        $content = Get-Content $FilePath -Raw -Encoding UTF8
        foreach ($ph in $Placeholders) {
            if ($content -match [regex]::Escape($ph)) { return $false }
        }
        return $true
    } catch {
        return $false
    }
}

# === Step Execution Functions ===

function Invoke-AutoStep {
    param($Step)
    $verify = $Step.verify
    $t = $verify.type

    if ($t -eq "commands") {
        foreach ($c in $verify.commands) {
            Write-Host ("         > " + $c.cmd)
            $r = & Invoke-Expression $c.cmd 2>&1
            if ($LASTEXITCODE -ne 0) {
                Write-Host ("         [FAIL] " + $c.fail_message) -ForegroundColor Red
                return $false
            } else {
                Write-Host ("         [OK]   " + $r)
            }
        }
        return $true
    }
    elseif ($t -eq "dir_exists") {
        $p = $verify.path
        if (-not (Test-Path $p)) {
            New-Item -ItemType Directory -Force -Path $p | Out-Null
            if (-not (Test-Path $p)) {
                Write-Host ("         [FAIL] " + $verify.fail_message) -ForegroundColor Red
                return $false
            }
        }
        Write-Host ("         [OK]   " + $p + " exists")
        return $true
    }
    elseif ($t -eq "file_exists") {
        $p = $verify.path
        if (Test-Path $p) {
            Write-Host ("         [OK]   " + $p + " exists")
            return $true
        } else {
            Write-Host ("         [FAIL] " + $verify.fail_message) -ForegroundColor Red
            return $false
        }
    }
    elseif ($t -eq "command_exit_zero") {
        $cmd = $verify.cmd
        Write-Host ("         > " + $cmd)
        $r = & Invoke-Expression $cmd 2>&1
        if ($LASTEXITCODE -ne 0) {
            Write-Host ("         [FAIL] " + $verify.fail_message) -ForegroundColor Red
            return $false
        }
        Write-Host "         [OK]   Command succeeded"
        return $true
    }
    elseif ($t -eq "any_of") {
        Write-Host "         [OK]   (auto-pass)"
        return $true
    }
    else {
        Write-Host ("         [WARN] Unknown type: " + $t) -ForegroundColor Yellow
        return $false
    }
}

function Invoke-VerifyStep {
    param($Step)
    $verify = $Step.verify
    $t = $verify.type

    if ($t -eq "file_exists") {
        $p = $verify.path
        if (Test-Path $p) {
            Write-Host ("         [OK]   " + $p + " exists")
            return $true
        } else {
            Write-Host ("         [INFO] " + $verify.fail_message) -ForegroundColor Yellow
            return $false
        }
    }
    elseif ($t -eq "yaml_fields_not_empty") {
        if (Test-YamlFields -FilePath $verify.path -Fields $verify.fields) {
            Write-Host "         [OK]   All required fields filled"
            return $true
        } else {
            Write-Host ("         [INFO] " + $verify.fail_message) -ForegroundColor Yellow
            return $false
        }
    }
    elseif ($t -eq "no_placeholder_in_file") {
        if (Test-NoPlaceholder -FilePath $verify.path -Placeholders $verify.placeholders) {
            Write-Host "         [OK]   No placeholders found"
            return $true
        } else {
            Write-Host ("         [INFO] " + $verify.fail_message) -ForegroundColor Yellow
            return $false
        }
    }
    elseif ($t -eq "noop") {
        Write-Host ("         [INFO] " + $verify.description) -ForegroundColor Yellow
        return $false
    }
    else {
        Write-Host ("         [WARN] Unknown type: " + $t) -ForegroundColor Yellow
        return $false
    }
}

# === Main ===

Write-Host ""
Write-Host "================================================"
Write-Host " iteration-workflow Project Init Wizard"
Write-Host "================================================"
Write-Host ""

$Checklist = Parse-Yaml -FilePath $ChecklistFile
$Steps = $Checklist.steps
$TotalSteps = $Steps.Count
$StepIndex = 0
$State = Load-State -FilePath $StateFile

if ($DryRun) {
    Write-Host "  MODE: DRY RUN (preview only)"
    Write-Host ""
}

$pendingFound = $false
$hadError = $false

foreach ($step in $Steps) {
    $StepIndex++
    $id = $step.id
    $name = $step.name
    $type = $step.type
    $status = "pending"
    if ($State.ContainsKey($id)) { $status = $State[$id] }
    $pfx = ("[" + $StepIndex + "/" + $TotalSteps + "]")

    if ($DryRun) {
        $sym = "[---]"
        if ($status -eq "completed") { $sym = "[OK]  " }
        elseif ($status -eq "failed") { $sym = "[FAIL]" }
        elseif ($status -eq "skipped") { $sym = "[SKIP]" }
        $nt = $type.ToUpper()
        if ($type -eq "manual" -and $status -ne "completed") { $nt = "MANUAL *" }
        Write-Host ($pfx + " " + $sym + " " + $name + " [" + $nt + "]")
        if ($type -eq "manual" -and $status -ne "completed" -and $step.hints) {
            foreach ($h in $step.hints) {
                Write-Host ("         -> " + $h)
            }
        }
        continue
    }

    if ($status -eq "completed") {
        Write-Host ($pfx + " [OK]   " + $name + " [COMPLETED]")
        continue
    }
    if ($status -eq "skipped") {
        Write-Host ($pfx + " [SKIP] " + $name + " [SKIPPED]")
        continue
    }

    $depBlocked = $false
    if ($step.depends) {
        foreach ($d in $step.depends) {
            $ds = "pending"
            if ($State.ContainsKey($d)) { $ds = $State[$d] }
            if ($ds -ne "completed" -and $ds -ne "skipped") { $depBlocked = $true; break }
        }
    }
    if ($depBlocked) {
        Write-Host ($pfx + " [WAIT] " + $name + " (dependency pending)")
        $pendingFound = $true
        continue
    }

    if ($type -eq "auto") {
        Write-Host ($pfx + " [RUN]  " + $name + " [AUTO]")
        if (Invoke-AutoStep -Step $step) {
            $State[$id] = "completed"; Save-State -FilePath $StateFile -State $State
        } else {
            $State[$id] = "failed"; Save-State -FilePath $StateFile -State $State
            $hadError = $true; $pendingFound = $true
            break
        }
    }
    elseif ($type -eq "manual") {
        Write-Host ($pfx + " [CHK]  " + $name + " [MANUAL]")
        if (Invoke-VerifyStep -Step $step) {
            $State[$id] = "completed"; Save-State -FilePath $StateFile -State $State
            Write-Host ($pfx + " [OK]   " + $name + " [COMPLETED]")
        } else {
            Write-Host ($pfx + " [----] " + $name + " [PENDING]")
            if ($step.hints) {
                foreach ($h in $step.hints) { Write-Host ("         -> " + $h) }
            }
            Write-Host "         !! Re-run this script after completing."
            $pendingFound = $true
            break
        }
    }
    else {
        # verify type
        Write-Host ($pfx + " [CHK]  " + $name + " [VERIFY]")
        if (Invoke-VerifyStep -Step $step) {
            $State[$id] = "completed"; Save-State -FilePath $StateFile -State $State
        } else {
            $State[$id] = "failed"; Save-State -FilePath $StateFile -State $State
            $hadError = $true; $pendingFound = $true
        }
    }
}

Write-Host ""
if ($DryRun) {
    $done = 0
    foreach ($k in $State.Keys) { if ($State[$k] -eq "completed") { $done++ } }
    Write-Host ("  Preview done. Completed: " + $done + " / " + $TotalSteps)
} elseif (-not $pendingFound) {
    Write-Host "  All steps complete! Project initialized successfully."
} else {
    $done = 0
    foreach ($k in $State.Keys) { if ($State[$k] -eq "completed") { $done++ } }
    Write-Host ("  Progress: " + $done + " / " + $TotalSteps + " completed")
}

if (-not $DryRun) {
    Write-Host ("  State file: " + $StateFile)
}
Write-Host ""
